name: production-deploy
on: [workflow_dispatch]
jobs:
  deploy_prodiction:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - run: gem install shopify-cli
      - run: shopify login --store=$PRODUCTION_STORE --password=$PRODUCTION_PASSWORD
      - run: shopify theme push --allow-live --nodelete --theme $PRODUCTION_THEME_ID
env:
  PRODUCTION_THEME_ID: ${{ secrets.PRODUCTION_THEME_ID }}
  PRODUCTION_PASSWORD: ${{ secrets.PRODUCTION_ADMIN_API_ACCESS_TOKEN }}
  PRODUCTION_STORE: ${{ secrets.PRODUCTION_STORE }}
  CI: true # Special flag necessary to operate shopify-cli in "CI" mode
